#!/bin/bash
FILE=bin/entradasalida
CONFIG_FILE=${1:-./cfg/GENERICA.config}
NOMBRE_INTERFAZ=${2:-GENERICA}

make clean all
make

if test -f "./$FILE"; then
    ./$FILE "$CONFIG_FILE" "$NOMBRE_INTERFAZ"
fi