#!/bin/bash
FILE=bin/entradasalida
CONFIG_FILE=${1:-./cfg/io_generica.config}
NOMBRE_INTERFAZ=${2:-eth0}

make clean all
make

if test -f "./$FILE"; then
    ./$FILE "$CONFIG_FILE" "$NOMBRE_INTERFAZ"
fi