#!/bin/bash
FILE=bin/entradasalida
CONFIG_FILE=${1:-./cfg/IO_GEN_SLEEP.config}
NOMBRE_INTERFAZ=${2:-IO_GEN_SLEEP}

make clean all
make

if test -f "./$FILE"; then
    ./$FILE "$CONFIG_FILE" "$NOMBRE_INTERFAZ"
fi