#!/bin/bash
FILE=bin/entradasalida
CONFIG_FILE=${1:-./cfg/MONITOR.config}
NOMBRE_INTERFAZ=${2:-MONITOR}

make clean all
make

if test -f "./$FILE"; then
    ./$FILE "$CONFIG_FILE" "$NOMBRE_INTERFAZ"
fi