#!/bin/bash
FILE=bin/entradasalida
CONFIG_FILE=${1:-./cfg/entradasalida.config}

make clean all
make
if test -f "./$FILE"; then
    valgrind --tool=memcheck --leak-check=yes --show-possibly-lost=yes --show-reachable=no --num-callers=20 --track-origins=yes ./$FILE "$CONFIG_FILE"
fi