#!/bin/bash
FILE=bin/entradasalida
CONFIG_FILE=${1:-./cfg/FS.config}
NOMBRE_INTERFAZ=${2:-FS}

make clean all
make

if test -f "./$FILE"; then
    valgrind --leak-check=full ./$FILE "$CONFIG_FILE" "$NOMBRE_INTERFAZ"
fi